version: "3.8"

services:
  web:
    build:
      context: .
      target: prod-stage
    environment:
      DJANGO_SETTINGS_MODULE:
      SECRET_KEY:
      ALLOWED_HOSTS:
      DATABASE_URL:
    depends_on:
     - db

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
