version: "3.8"

services:
  web:
    build:
      target: dev-stage
      args:
        PYTHON_IMAGE_TAG: 3.8
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"

  celery-beat:
    build:
      target: dev-stage
      args:
        PYTHON_IMAGE_TAG: 3.8
    command: celery -A config beat -l info
