version: "3.8"

services:
  web:
    build:
      context: .
      target: prod-stage
    environment:
      DJANGO_SETTINGS_MODULE:
      SECRET_KEY:
      ALLOWED_HOSTS:
      DATABASE_URL:
      REDIS_URL:
    depends_on:
     - db
     - redis

  celery-beat:
    build:
      context: .
      target: prod-stage
    environment:
      DJANGO_SETTINGS_MODULE:
      SECRET_KEY:
      ALLOWED_HOSTS:
      DATABASE_URL:
      REDIS_URL:
    depends_on:
      - redis

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine


volumes:
  db_data:
